WebApp_Pronia/WebApp_Pronia/Models/ErrorViewModel.cs
namespace WebApp_Pronia.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp_Pronia/WebApp_Pronia/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Pronia.Business.Exceptions;
using Pronia.Business.Services.Abstracts;
using Pronia.Core.Models;

namespace WebApp_Pronia.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IActionResult Index()
        {
            var categories=_categoryService.GetAllCategories();
            return View(categories);
        }
        public IActionResult Create() 
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category category)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                _categoryService.AddCategory(category);
            }
            catch (DuplicateCategoryException ex)
            {
                ModelState.AddModelError(ex.PropertyName,ex.Message);          
                return View();
            }
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            var category=_categoryService.GetCategory(x => x.Id == id);
            return View(category);
        }
        [HttpPost]
        public IActionResult Update(Category category)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                _categoryService.Update(category.Id, category);
            }
            catch (DuplicateCategoryException ex)
            {

                ModelState.AddModelError(ex.PropertyName,ex.Message);
                return View();
            }
            
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id) 
        {
            _categoryService.DeleteCategory(id);           
            return RedirectToAction("Index");
        }
    }
}

WebApp_Pronia/WebApp_Pronia/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp_Pronia.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApp_Pronia/WebApp_Pronia/Areas/Admin/Controllers/SliderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.Business.Exceptions;
using Pronia.Business.Services.Abstracts;
using Pronia.Business.Services.Concretes;
using Pronia.Core.Models;

namespace WebApp_Pronia.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SliderController : Controller
    {
        private readonly ISliderService _sliderService;
        IWebHostEnvironment _environment;
        public SliderController(ISliderService sliderService, IWebHostEnvironment environment)
        {
            _sliderService = sliderService;
            _environment = environment;
        }

        public IActionResult Index()
        {
            var sliders=_sliderService.GetAllSliders();
            return View(sliders);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Slider slider)
        {
            if (!slider.ImageFile.ContentType.Contains("image/"))
            {
                ModelState.AddModelError("PhotoFile", "Formati duzgun daxil edin");
                return View();
            }


            string filename = slider.ImageFile.FileName;
            string path = _environment.WebRootPath + @"\Upload\Slider\" + filename;
            using (FileStream stream = new FileStream(path, FileMode.Create))
            {
                slider.ImageFile.CopyTo(stream);

            }


            slider.ImgUrl = filename;


            if (!ModelState.IsValid)
            {
                return View();
            }
            _sliderService.AddSlider(slider);
           
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            _sliderService.DeleteSlider(id);
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            var slider=_sliderService.GetSlider(x=>x.Id==id);
            return View(slider);
         
        }
        [HttpPost]
        public IActionResult Update(Slider slider)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                _sliderService.UpdateSlider(slider.Id, slider);
            }
            catch (DuplicateCategoryException ex)
            {

                ModelState.AddModelError(ex.PropertyName, ex.Message);
                return View();
            }

            return RedirectToAction("Index");
        }
    }
}

WebApp_Pronia/WebApp_Pronia/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp_Pronia.Models;

namespace WebApp_Pronia.Controllers
{
    public class HomeController : Controller
    {
        

        public IActionResult Index()
        {

            return View();
        }

      
    }
}

WebApp_Pronia/WebApp_Pronia/Areas/Admin/Views/Category/Create.cshtml
@model Category
<div class="container">
    <form method="post">
        <div class="mb-3">
            <label asp-for="Name" class="form-label">Name</label>
            <input asp-for="Name" class="form-control">
            <span asp-validation-for="Name" style="color:red"></span>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

WebApp_Pronia/WebApp_Pronia/Areas/Admin/Views/Category/Index.cshtml
@model List<Category>
@{
    int count = 0;
}
<div class="container">
    <h1>

        Category
        <a class="btn btn-primary" asp-action="Create" asp-controller="Category">Create</a>

    </h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                count++;
                <tr>
                    <td>@count</td>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    
                    <td>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Category" asp-route-id=@item.Id>Delete</a>
                        <a class="btn btn-info" asp-action="Update" asp-controller="Category" asp-route-id=@item.Id>Update</a>
                    </td>

                </tr>
            }



        </tbody>
    </table>
</div>

WebApp_Pronia/WebApp_Pronia/Areas/Admin/Views/Category/Update.cshtml
@model Category
<div class="container">
    <form method="post">
        <div class="mb-3">
            <label asp-for="Name" class="form-label">Name</label>
            <input asp-for="Name" class="form-control">
            <span asp-validation-for="Name" style="color:red"></span>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

WebApp_Pronia/WebApp_Pronia/Areas/Admin/Views/Slider/Create.cshtml
@model Slider
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="mb-3 col-md-4">
                <label asp-for="Title" class="form-label">Title</label>
                <input asp-for="Title" class="form-control">
                <span asp-validation-for="Title" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-4">
                <label asp-for="SubTitle" class="form-label">SubTitle</label>
                <input asp-for="SubTitle" class="form-control">
                <span asp-validation-for="SubTitle" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-4">
                <label asp-for="ImageFile" class="form-label">ImgUrl</label>
                <input asp-for="ImageFile" class="form-control">
                <span asp-validation-for="ImageFile" style="color:red"></span>
            </div>
        </div>
        <div class="mb-3">
            <label asp-for="Description" class="form-label">Description</label>
            <textarea class="form-control" asp-for="Description" rows="3"></textarea>
            <span asp-validation-for="Description" style="color:red"></span>

        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

WebApp_Pronia/WebApp_Pronia/Areas/Admin/Views/Slider/Index.cshtml
@model List<Slider>
@{
    int count = 0;
}
<div class="container">
    <h1>

        Slider
        <a class="btn btn-primary" asp-action="Create" asp-controller="Slider">Create</a>

    </h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">SubTitle</th>
                <th scope="col">Description</th>
                <th scope="col">Image</th>


            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                count++;
                <tr>
                    <td>@count</td>
                    <td>@item.Title</td>
                    <td>@item.SubTitle</td>

                    <td>@item.Description</td>
                    <td>
                        <div style="width:100px">
                            <img width="100%" src="~/Upload/Slider/@item.ImgUrl"></img>
                        </div>
                    </td>




                    <td>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Slider" asp-route-id=@item.Id>Delete</a>
                        <a class="btn btn-info" asp-action="Update" asp-controller="Slider" asp-route-id=@item.Id>Update</a>
                    </td>

                </tr>
            }



        </tbody>
    </table>
</div>

WebApp_Pronia/WebApp_Pronia/Areas/Admin/Views/Slider/Update.cshtml
@model Slider
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="mb-3 col-md-4">
                <label asp-for="Title" class="form-label">Title</label>
                <input asp-for="Title" class="form-control">
                <span asp-validation-for="Title" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-4">
                <label asp-for="SubTitle" class="form-label">SubTitle</label>
                <input asp-for="SubTitle" class="form-control">
                <span asp-validation-for="SubTitle" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-4">
                <label asp-for="ImageFile" class="form-label">ImgUrl</label>
                <input asp-for="ImageFile" class="form-control">
                <span asp-validation-for="ImageFile" style="color:red"></span>
            </div>
        </div>
        <div class="mb-3">
            <label asp-for="Description" class="form-label">Description</label>
            <textarea class="form-control" asp-for="Description" rows="3"></textarea>
            <span asp-validation-for="Description" style="color:red"></span>

        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>